txt = """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkkkkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc;,,,,'';o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOl,';coxxxxoc,;o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0l,':dOKXXXXXX0xc,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,':d0KXXXXXXXXXKOl,,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.'lOKXXXXXXXXXXXXKOl''oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c',o0KXXXXXXXXXXXXXXKk:.;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.,d0XXXXXXXXXXXXXXXXXKx,.c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l''dKXXXXXXXXXXXXXXXXXXX0c.'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd,'lOXXXXXXXXXXXXXXXXXXXXKx,.:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;'ckKXXXXXXXXXXXXXXXXXXXXKOl.;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl';xKXXXXXXXXXXXXXXXXXXXXXXKd,'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo''o0KXXXXXXXXXXXXXXXXXXXXXXKkc.;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;'ckKXXXXXXXXXXXXXXXXXXXXXXXXOl.,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl';xKXXXXXXXXXXXXXXXXXXXXXXXXX0d,.c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:,o0XXXXXXXXXXXXXXXXXXXXXXXXXXKk:.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl,ckKXXXXXXXXXXXXXXXXXXXXXXXXXXX0d,'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,,dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXKOc':ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:'cOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKx;'lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo',d0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOl''dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,'cOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKx,.c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo',dKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c.,xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,'lOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd,.c0WMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.;xKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc.:OXX0OkkkxxkKNWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,'cOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0o'.;:;'''''''';coONWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.,xKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKx;..':cclllllc:;,;lONMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo'.c0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOl..;odddddddddol:,,o0WMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0x,.'coddddddddddoc,':ONMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,.;xKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0kdc....,;;:clodddddol:,;o0NMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..l0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0Oxol:,'''. .';c:,,;:loddddol:,:okKNWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.,d0KXXXXXXXXXXXXXXXXXXXXXKKKK0Okdoc:,'.'';:cc,..c0WX0xc,',:lodddolc;,:oONWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl...;ldxO0KKXXXXXXXXXKK00Okxdolc;,'''',,;:ccllll:..,xXWMWNOo;,,;coodolc;,,:o0NMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..:::;,;:codkOOOkxxdoc:;,'''''',;;::cccllllllllc;. 'oXWMMMNXOo;,,:clllc:,.'c0WMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.;lddolc:,,,,,,'.......',;:::cccccccccccccc::;;,'...c0WMMMMMMWKOoc;;;:c:,';xXWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.:oddddddoolc:;,'............''''''''''''''..'',;:;';xXMMMMMMMMMWXKkdl:;:lONMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..:loodddddddddooooollcc::;;;,,,,,,,,,,;;::ccllooooc''lKMMMMMMMMMMMMMWNK0KNWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNd'..'',;:cloodddddddddddddddddddddddddddddddddddddddoc'.cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWKc..,:;,''..'',;:clllooooooooddddddddddddddddddooooooo:'.cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMXd'..,,,,''........''',,,;;;;::::ccccccccccccc::::;;;;,..,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKl.'lolc::::::cllodxddolcc:;;,,,,,,,,''',,,,,;;;;::clol;.c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWWWWWWWWWWOc'cOKKK000000KKKXXXXXKKKK000OOOOOOkkxxxxkkOOOOO000KKK0d;,oKWWWWWWWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWNXKOxxdddoooddoc'.;oxxxkkOOO00000KKKKKKKXXXXXXKKKKKKK000000OOOOOOOkkkko;.':dxxxxxxxk0KXXNWMMMMMMMMMMMMMMM
MMMMMMMMWKxc;;,,;;;::cccccc:;;::;;,,,',;;;:ccclllllooooolllllccc::;;;,,'''',,,,,,;,',;;:::;;;,,,,;;coxOKNMMMMMMMMMMM
MMMMMMMWOc..':odxkOO0KKKKKKKKK00Okkxdoolllcccc:;;;;;;;;;;;;;;::ccccllllooodddxxxkkOO0000000OOkxdol:,...c0WMMMMMMMMMM
MMMMMMMW0o;',,,;;::ccclloodxxkkOOO0000000000000OOO0000000000000000000000000O000OOOkkkkkkxxdoollcc:;,'.,lKWMMMMMMMMMM
MMMMMMMMWNK0Odolllllcccc:,,'...''''',,;;;;::ccccccclllllllccccccc:::;;;;,,,'',,,,''.'',,,,,,:cccclldxOKXWMMMMMMMMMMM
MMMMMMMMMMMMMWWWWWWWWWNNXKOo,.;lollcccccc::::::::::::::::::::::::::ccccccclllloool;.'lxOOO0KXNNNWWWWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMXx,,oO0OOOOOOOOOOOOkkOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOko,;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKo.,dOOOOkxolllldxOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOOOOOOx;'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKl.,xOOOdc;;:llc::lxOOOOOOOOOOOOOOOOOOOOOOOkoc::cccldkOOkc',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMW0c.,xOOx:,lOXNNXkc;okOOOOOOOOOOOOOOOOOOOOOkl,;ok0Oxc;cxOOo,.lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNk;.;k0Od,;xXWMMW0l;lkOOOOOOOOOOOOOOOOOOOOOx:'l0WMMNx;,oOOx:.,kNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXo'.:k0Oxc,;d0KKkl;:dkOOOxodkOOOxdddkOOOOOOkl,:x0XX0o,;oOOkl.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWKl..ckOOOxl;;:::;;cdkOOOdc:oOOOkdl::xOOOOOOOxl;;:cc:;:okOOOd,.:OWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWWNNWWWWNNNXk:.'lOOOOOOkxdddxxkOOOOxc;cxOkkkdl;,okOOOOOOOkxdollodkOOOO0x:.'xXMMMMMMMWWNNNNXK0kkxxxkkO0X
MMMMMWWNK0Okxolcloxxdlcc:,..,oOOOOOOOOOOOOOOOOOOd;,okxllxdo:,cxOOOOOOOOOOOOOOOOOOOOOkl'.oKNNK0OOkxoccc::;''.....'',;
MWNKOdlc:,,;;;;;;;:::clllc'.,dOOOOOOOOOOOOOOOOOko',dko;;oxxl,;oOOOOOOOOOOOOOOOOOOOOOOo'.':cc:;;;;:::cclloodddddddool
Oxc,',;coxkOO0000000KKKKKk;.;dOOOOOOOOOOOOOOOOOko',oko,'ckOd;'cxOOOOOOOOOOOOOOOOOOOOOx;..;lodxkO000KKKKKKXXXXXXXXXKK
..,cdk0KXXXXXXXXXXXXXXXXKx;.:xOOOOOOOOOOOOOOOOOOd;,cdl'.:xOkc';oOOOOOOOOOOOOOOOOOOOOOkc',dKXXXXXXXXXXXXXXXXXXXXXXXXX
;oOKXXXXXXXXXXXXXXXXXXXXKx,.:xOOOOOOOOOOOOOOOOOOkc,,::. 'lxxl,,oOOOOOOOOOOOOOOOOOOOOOkl''l0KXXXXXXXXXXXXXXXXXXXXXXXX
0KXXXXXXXXXXXXXXXXXXXXXX0d,.ckOOOOOOOOOOOOOkkkOOOxl,'',,,',;,':xOOxoxOOOOOOOOOOOOOOOOOo,.:OKXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX0d,.lkOOOOOOOOOOOOkdclxOOOkxodxkdlc:clxOOkc;lkOOOOOOOOOOOOOOOOd;.;kKXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX0o,.lkOOOOOOOOOOOOOd;,oOOOOOOOOOOOOOOOOOOxc':xOOOOOOOOOOOOOOOOxc.,dKXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX0l''lkOOOOOOOOOOOOOd;.ckOOOOOOOOOOOOOOOOOkc',oOOOOOOOOOOOOOOOOkl''l0XXXXXXXXXXXXXXXXXXXXXXXX
XKKKXXXXXXXXXXXXXXXXXXXX0l',oOOOOOOOOOOOOOkl'.,coxkOOOOOOOOOOOOkdl;..;dOOOOOOOOOOOOOOOOo,.cOXXXXXXXXXXXXXXXXXXXXXXXX
0xk0XXXXXXXXXXXXXXXXXXXX0l',oOOOOOOOOOOOOOd;';c:;;;:clloooollc:;;;cl;,:okOOOOOOOOOOOOOOd;.;OXXXXXXXXXXXXXXXXXXXXXXXX
dokKXXXXXXXXXXXXXXXXXXXX0l',oOOOOOOOOOOOOd:,:dkkxdlc::;;,;;;::codkOOxl:cdkOOOOOOOOOOOOOx:.,kXXXXXXXXXXXXXXXXXXXXXXXX
cd0XXXXXXXXXXXXXXXXXXXXX0l',oOOOOOOOOOOOxc;cxOOOOOOOOkkxxxkkkOOOOOOOOkkxkOOOOOOOOOOOOOOkl.'xKXXXXXXXXXXXXXXXXXXXXXXX
cOXXXXXXXXXXXXXXXXXXXXXX0l,;oOOOOOOOOOOOkxxkOOOOOOOOOkkxxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOko,'d0XXXXXXXXXXXXXXXXXXXXXXX
d0XXXXXXXXXXXXXXXXXXXXXX0d;:dOOOOOOOOOOOOOOOOOOOOOkdc:;;;;;:coxOOOOOOOOOOOOOOOOOOOOOOOOOd;'l0XXXXXXXXXXXXXXXXXXXXXXX
x0XXXXXXXXXXXXXXXXXXXXXX0d::dOOOOOOOOOOOOOOOOOOOOxl;;cloollc;;cdOOOOOOOOOOOOOOOOOOOOOOOOx:'cOXXXXXXXXXXXXXXXXXXXXXXX
OKXXXXXXXXXXXXXXXXXXXXXX0d;;oOOOOOOOOOOOOOOOOOOOOxddkOOOOOOOkxdxOOOOOOOOOOOOOOOOOOOOOOOOkc',lk0KXXXXXXXXXXXXXXXXXXXX
OKXXXXXXXXXXXXXXXXXXXXXX0o''lkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd;...,;okO0OOkxxxxkOKXXXXXXX
OKXXXXXXXXXXXXXXXXXXXXXOo,.',cdkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxoc;,;:odl;''',''.....',:oxOOkxd
OKXXXXXXXXXXXXXXXXXXXKkc''lxo:;:codxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxdlc:;;:ldO0KXKkc.  .',;;;;,'....',;;
OKXXXXXXXXXXXXXXXXXXXOl..:kKKkl;'',:oxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOxdl;'..,cdO0KXXXXKkl,...,:clllcc;.. .cxk
"""

if __name__ == "__main__": #so it doesnt run when imported
    print(txt)
    input()
